sudo: required

dist: bionic

os: linux

language: python

python:
- "2.7"

before_install:
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5
- sudo apt update -qq
- sudo DEBIAN_FRONTEND=noninteractive apt-get install -y kicad imagemagick
- pip install pcb-tools image

before_script:
- export PYTHONPATH=$PYTHONPATH:"/usr/lib/python2.7/dist-packages"

script:
- python scripts/pslab_gerber_generator.py

after_success:
- bash scripts/check-diffs.sh
